### ISSUE TITLE
document how to contribute

### ISSUE THREAD

**Issue by deanmalmgren** [edeno/d3-save-svg#3]
I would have made a pull request, but I didn't have the time to figure out how the build process works, how I could test that things were working properly, etc. If you could put that in a CONTRIBUTING.md or directly in the README.md, it'd be a lot easier to help out :)

**Comment by edeno** [comment]
Okay done. Let me know if you need any more information.

**Comment by deanmalmgren** [comment]
Looks good to me. I'm a little swamped at the moment but, if I get a chance, I'll see if I can't add PNG support (unless you beat me to it!). Thanks for bringing this project to my attention. I'm grateful you took the initiative to make it happen :)
